name: 'Terraform'

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'notebooks/**'
      - '**/*.tf'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'notebooks/**'
      - '**/*.tf'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_VAR_databricks_host: ${{ secrets.DATABRICKS_HOST }}
  TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}

permissions:
  contents: read
  pull-requests: write
  actions: write  # Required for caching

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'

    - name: Setup Terraform Cache
      uses: actions/cache@v3
      with:
        path: .terraform/terraform.tfstate
        key: ${{ runner.os }}-tfstate-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-tfstate-

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: |
        # Create .terraform directory if it doesn't exist
        mkdir -p .terraform
        
        # Check if we have a cached state file
        if [ -f .terraform/terraform.tfstate ]; then
          echo "Using cached Terraform state"
          cp .terraform/terraform.tfstate terraform.tfstate 2>/dev/null || true
        fi
        
        terraform init
        terraform plan -no-color -input=false \
          -var="databricks_host=${{ env.TF_VAR_databricks_host }}" \
          -var="databricks_token=${{ env.TF_VAR_databricks_token }}"
          
        # Save the state file back to the cache directory
        if [ -f terraform.tfstate ]; then
          cp terraform.tfstate .terraform/terraform.tfstate
        fi

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Create .terraform directory if it doesn't exist
        mkdir -p .terraform
        
        # Check if we have a cached state file
        if [ -f .terraform/terraform.tfstate ]; then
          echo "Using cached Terraform state"
          cp .terraform/terraform.tfstate terraform.tfstate 2>/dev/null || true
        fi
        
        terraform init
        terraform apply -auto-approve -input=false \
          -var="databricks_host=${{ env.TF_VAR_databricks_host }}" \
          -var="databricks_token=${{ env.TF_VAR_databricks_token }}"
          
        # Save the state file back to the cache directory
        if [ -f terraform.tfstate ]; then
          cp terraform.tfstate .terraform/terraform.tfstate
        fi
